site: herr-breier.de
title: Herr-Breier.de Blog
description: >-
  just a minimalist, personal blog
googlewebfonts: Fira+Code:wght@400;500;700
lang: en-US
timezone: Berlin
  #repo: https://github.com/p0wex/Gesko # site repo [optional]
data-theme: dark # default theme "dark" | "light"

author:
  name: David Breier
  bio: just a minimalist, personal blog, mainly about IT topics
  username: dave # general username
  github: Kurugit # github username
    #twitter: P0Wex # twitter username
  email: david.breier@outlook.de # email adress

# URL settings
#url: "https://herr-breier.de" #
#  baseurl: "/Gesko" # leave blank if not wishd
#  permalink: "https://herr-breier.de/Gesko/"
permalink: pretty 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


